# Autogenerated wrapper script for BinaryPlayground_jll for x86_64-linux-musl
export binary_playground, libbinary_playground

JLLWrappers.@generate_wrapper_header("BinaryPlayground")
JLLWrappers.@declare_library_product(libbinary_playground, "libbinary_playground.so")
JLLWrappers.@declare_executable_product(binary_playground)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libbinary_playground,
        "lib/libbinary_playground.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        binary_playground,
        "bin/binary_playground",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
